/**
 * AgentFlow built-in workflow templates.
 *
 * Each template is the unit of value the consultant resells. Keep them:
 *  - Self-contained (every render only needs `params`).
 *  - Honest about scope (`inputs` / `outputs` / `excludes`).
 *  - Priced as a range with a "why this range" note for the consultant.
 *
 * Render outputs (python / n8n / readme) use `{{paramName}}` placeholders.
 * The bundler resolves them via `renderTemplate` in `bundler.ts`.
 */

export type TemplateComplexity = "simple" | "medium" | "complex";

export interface TemplateParamSpec {
  key: string;
  label: string;
  hint?: string;
  default?: string;
  multiline?: boolean;
}

export interface TemplateRoi {
  /** Sample headline used in diagnostic reports, e.g. "每月节省 40 小时 / 客户成本 ¥6,000+" */
  headline: string;
  /** Free-form formula doc rendered into report. */
  formula: string;
}

export interface Template {
  slug: string;
  name: string;
  short: string;
  industry: string[];
  complexity: TemplateComplexity;
  estDays: number;
  priceCents: [number, number];
  monthlyCents: [number, number];
  /** What the client needs to hand over before we start. */
  inputs: string[];
  /** What ends up in the zip the client receives. */
  outputs: string[];
  /** Out-of-scope statements (manage expectations early). */
  excludes: string[];
  /** Why this scope sits in this price band — for the consultant, not the client. */
  pricingNote: string;
  roi: TemplateRoi;
  params: TemplateParamSpec[];
  pythonTemplate: string;
  n8nTemplate: Record<string, unknown>;
  readmeTemplate: string;
}

const COMMON_PYTHON_HEADER = `#!/usr/bin/env python3
"""Generated by AgentFlow — {{templateName}}
Client: {{clientName}}
Project: {{projectName}}
Generated at: {{generatedAt}}

This script is delivered as part of the {{templateName}} pilot. Read the
accompanying README.md before running.
"""

import os
import sys
import json
from typing import Any, Dict, List, Optional
`;

export const TEMPLATES: Template[] = [
  {
    slug: "lead-intake",
    name: "销售线索自动录入",
    short: "网页表单 / 邮件 / 微信消息 → AI 提取关键字段 → 写入表格 + 推送通知",
    industry: ["通用 B2B", "外贸", "本地服务"],
    complexity: "simple",
    estDays: 3,
    priceCents: [200000, 500000],
    monthlyCents: [50000, 100000],
    inputs: [
      "需要支持的线索来源（如表单链接 / 邮箱 / 群消息截图样本）",
      "目标表格地址（飞书多维表 / 钉钉宜搭 / Google Sheet 任选）",
      "通知渠道（钉钉群 / 企业微信群机器人 Webhook）",
      "字段映射规则（哪些字段要提取，哪些要打标签）",
    ],
    outputs: [
      "Python 脚本（含 LLM 调用）+ requirements.txt",
      "n8n 工作流 JSON（可直接导入 n8n 启动）",
      "客户使用手册 Markdown",
    ],
    excludes: [
      "不包含线索来源的爬取（仅支持客户已提供的 webhook / 转发邮件）",
      "不包含 CRM 系统的开发（写入既有表格即可）",
    ],
    pricingNote: "通用度最高、复杂度最低；适合作为 hook 产品，1-3 天内可交付。",
    roi: {
      headline: "每条线索处理时间从 2-3 分钟降至 5 秒，每月节省 10-30 小时",
      formula: "节省工时 = 月线索数 × (人工耗时 - 自动化耗时) ÷ 60，对应人力成本按 100 元/小时估算",
    },
    params: [
      { key: "leadFields", label: "需要提取的字段（逗号分隔）", default: "公司名,联系人,电话,邮箱,需求描述,预算" },
      { key: "notifyWebhook", label: "通知 Webhook URL", default: "https://oapi.dingtalk.com/robot/send?access_token=XXX" },
      { key: "sheetUrl", label: "目标表格地址", default: "https://feishu.cn/base/xxxxx" },
      { key: "llmModel", label: "使用的 LLM 模型", default: "claude-sonnet-4-6" },
    ],
    pythonTemplate: `${COMMON_PYTHON_HEADER}
import anthropic

LEAD_FIELDS = "{{leadFields}}".split(",")
NOTIFY_WEBHOOK = "{{notifyWebhook}}"
SHEET_URL = "{{sheetUrl}}"
LLM_MODEL = "{{llmModel}}"

EXTRACTION_PROMPT = (
    "你是销售线索提取助手。从下面的原始文本中提取以下字段：\\n"
    + ", ".join(LEAD_FIELDS)
    + "\\n\\n用 JSON 输出，字段缺失则留空字符串。"
)

def extract_fields(raw: str) -> Dict[str, Any]:
    client = anthropic.Anthropic()
    msg = client.messages.create(
        model=LLM_MODEL,
        max_tokens=600,
        messages=[
            {"role": "user", "content": EXTRACTION_PROMPT + "\\n\\n原文：\\n" + raw},
        ],
    )
    text = msg.content[0].text  # type: ignore
    start = text.find("{")
    end = text.rfind("}")
    return json.loads(text[start : end + 1])

def write_to_sheet(record: Dict[str, Any]) -> None:
    """写入目标表格。默认通过 HTTP POST JSON 上送（飞书多维表格 / 钉钉宜搭 / Sheety / Apps Script 均兼容）。
    定制对接：替换 _write_via_http 或新增 _write_via_feishu / _write_via_dingtalk。"""
    import urllib.request
    body = json.dumps({"fields": record}, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(SHEET_URL, data=body, headers={"Content-Type": "application/json"}, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            print(f"[sheet] wrote record → status={resp.status}")
    except Exception as e:
        # 网络失败不阻塞通知；落到本地 jsonl 兜底，方便补录
        with open("lead_intake_failed.jsonl", "a", encoding="utf-8") as f:
            f.write(json.dumps({"record": record, "error": str(e)}, ensure_ascii=False) + "\\n")
        print(f"[sheet] FAILED → buffered to lead_intake_failed.jsonl: {e}")

def notify(record: Dict[str, Any]) -> None:
    import urllib.request
    body = json.dumps({"msgtype": "text", "text": {"content": f"新线索：{record.get('公司名','?')} - {record.get('需求描述','')[:50]}"}}).encode("utf-8")
    req = urllib.request.Request(NOTIFY_WEBHOOK, data=body, headers={"Content-Type": "application/json"})
    urllib.request.urlopen(req, timeout=5)

def main() -> int:
    raw = sys.stdin.read()
    if not raw.strip():
        print("usage: echo '线索原文' | python lead_intake.py", file=sys.stderr)
        return 2
    record = extract_fields(raw)
    write_to_sheet(record)
    notify(record)
    print(json.dumps(record, ensure_ascii=False, indent=2))
    return 0

if __name__ == "__main__":
    sys.exit(main())
`,
    n8nTemplate: {
      name: "AgentFlow - lead-intake",
      nodes: [
        { name: "Webhook", type: "n8n-nodes-base.webhook", parameters: { path: "lead-intake" }, position: [200, 200] },
        { name: "Anthropic Extract", type: "n8n-nodes-base.httpRequest", parameters: { url: "https://api.anthropic.com/v1/messages" }, position: [500, 200] },
        { name: "Append Row", type: "n8n-nodes-base.httpRequest", parameters: { url: "{{sheetUrl}}" }, position: [800, 200] },
        { name: "DingTalk Notify", type: "n8n-nodes-base.httpRequest", parameters: { url: "{{notifyWebhook}}" }, position: [1100, 200] },
      ],
      connections: {
        Webhook: { main: [[{ node: "Anthropic Extract", type: "main", index: 0 }]] },
        "Anthropic Extract": { main: [[{ node: "Append Row", type: "main", index: 0 }]] },
        "Append Row": { main: [[{ node: "DingTalk Notify", type: "main", index: 0 }]] },
      },
    },
    readmeTemplate: `# 销售线索自动录入

> 为 {{clientName}} 定制 · {{generatedAt}}

## 这是什么

把分散在表单、邮件、微信群里的销售线索原文，自动识别 → 提取关键字段 → 写入表格 → 推送通知给销售。

## 你需要做什么

1. 准备一个 Webhook 接收线索原文。
2. 配置 \`{{sheetUrl}}\` 对应表格的 API 访问凭证。
3. 配置 \`{{notifyWebhook}}\` 钉钉机器人 Webhook。

## 运行方式

### Python 单机版

\`\`\`bash
pip install anthropic
export ANTHROPIC_API_KEY=sk-ant-xxx
echo "客户的咨询原文" | python lead_intake.py
\`\`\`

### n8n 部署版

把 \`workflow.json\` 在 n8n 中导入。Webhook 节点的 URL 用作线索入口。

## ROI 估算

{{roiFormula}}

## 维护责任

- 客户：保证 webhook / 表格 / 机器人凭证有效。
- 顾问：模型升级与提取规则调优（包含在月度维护合同内）。
`,
  },

  {
    slug: "inquiry-reply",
    name: "外贸询盘智能回复",
    short: "客户询盘（含图片）→ AI 匹配历史产品 + 报价记录 → 生成回复草稿",
    industry: ["外贸", "玩具", "礼品", "电子产品"],
    complexity: "medium",
    estDays: 7,
    priceCents: [800000, 1500000],
    monthlyCents: [100000, 200000],
    inputs: [
      "近 3-6 个月的历史询盘原文（邮件、Trade Manager 截图、WhatsApp 文本）",
      "产品资料库（图片 + 尺寸 + 材质 + 认证 + MOQ + 包装规格 + 历史报价）",
      "至少 1 位资深业务员配合 2 小时审稿（标注好回复 vs 不好回复的范本）",
    ],
    outputs: [
      "向量化的产品 + 询盘知识库（Chroma 单机持久化）",
      "Python 命令行工具：粘贴询盘 → 输出回复草稿 + 报价建议",
      "可选：企业微信机器人 / 飞书 bot 集成脚本",
      "客户手册 + 业务员培训文档",
    ],
    excludes: [
      "不直接发送邮件给买家（草稿仍由业务员审核后发出）",
      "不替代 CRM（不做客户长期跟进、订单管理）",
      "不承诺成交率提升，只承诺响应速度与回复质量",
    ],
    pricingNote: "数据清洗 + 向量库 + 业务员协作是主要工时；玩具行业老板付费意愿强。",
    roi: {
      headline: "询盘响应时间从平均 15-30 分钟降至 2-5 分钟，业务员单兵日处理量翻倍",
      formula: "净收益 = 业务员人数 × 每日询盘数 × 节省分钟 × 60 ÷ 8 工作小时 × 人均日薪",
    },
    params: [
      { key: "productCatalogPath", label: "产品资料库目录", default: "./data/products" },
      { key: "historyInquiriesPath", label: "历史询盘归档目录", default: "./data/history-inquiries" },
      { key: "tone", label: "回复语气（professional / friendly / concise）", default: "professional" },
      { key: "languages", label: "支持语言（逗号分隔）", default: "en,zh" },
    ],
    pythonTemplate: `${COMMON_PYTHON_HEADER}
import anthropic
from pathlib import Path

PRODUCT_DIR = Path("{{productCatalogPath}}")
HISTORY_DIR = Path("{{historyInquiriesPath}}")
TONE = "{{tone}}"
LANGUAGES = "{{languages}}".split(",")

PROMPT = (
    "你是外贸玩具行业的资深业务员。根据下方产品资料 + 历史询盘范本，"
    "用 {tone} 语气，以 {lang} 写一封回复草稿，包含：产品确认、报价区间、MOQ、交货期、"
    "需要客户确认的下一步。不要承诺没把握的数字。"
)

def load_context() -> str:
    bits = []
    for p in PRODUCT_DIR.glob("**/*.md"):
        bits.append(f"# 产品资料: {p.name}\\n" + p.read_text(encoding="utf-8"))
    for p in HISTORY_DIR.glob("**/*.md"):
        bits.append(f"# 历史询盘范本: {p.name}\\n" + p.read_text(encoding="utf-8"))
    return "\\n\\n".join(bits)

def reply(inquiry: str, lang: str = "en") -> str:
    client = anthropic.Anthropic()
    msg = client.messages.create(
        model=os.environ.get("AGENTFLOW_MODEL", "claude-sonnet-4-6"),
        max_tokens=900,
        system=PROMPT.format(tone=TONE, lang=lang),
        messages=[
            {"role": "user", "content": "【知识库】\\n" + load_context() + "\\n\\n【客户询盘】\\n" + inquiry},
        ],
    )
    return msg.content[0].text  # type: ignore

if __name__ == "__main__":
    text = sys.stdin.read()
    lang = sys.argv[1] if len(sys.argv) > 1 else LANGUAGES[0]
    print(reply(text, lang))
`,
    n8nTemplate: {
      name: "AgentFlow - inquiry-reply",
      nodes: [
        { name: "Email Trigger", type: "n8n-nodes-base.emailReadImap", position: [200, 200] },
        { name: "Anthropic Reply", type: "n8n-nodes-base.httpRequest", parameters: { url: "https://api.anthropic.com/v1/messages" }, position: [500, 200] },
        { name: "Draft to Inbox", type: "n8n-nodes-base.emailSend", position: [800, 200] },
      ],
      connections: {
        "Email Trigger": { main: [[{ node: "Anthropic Reply", type: "main", index: 0 }]] },
        "Anthropic Reply": { main: [[{ node: "Draft to Inbox", type: "main", index: 0 }]] },
      },
    },
    readmeTemplate: `# 外贸询盘智能回复

> 为 {{clientName}} 定制 · {{generatedAt}}

## 干什么用

把买家询盘自动匹配你方的历史产品资料 + 优秀回复范本，秒出一份回复草稿。**业务员审核后发送**，不直接对外。

## 你需要准备

1. 把近 3 个月历史询盘（含你方的优秀回复）导出，放到 \`{{historyInquiriesPath}}\`。
2. 把产品资料（图片 + 参数）整理到 \`{{productCatalogPath}}\`，每个产品一份 \`.md\`。
3. 安装：\`pip install anthropic\` ，设置 \`ANTHROPIC_API_KEY\`。

## 使用方式

\`\`\`bash
echo "Hi, I'm looking for a unicorn plush toy, 20cm, 5000pcs, target price USD 2.5..." | python inquiry_reply.py en
\`\`\`

## 维护建议

- 每月把新的优秀回复回灌到知识库，保持答案与产品库同步。
- 月度维护合同建议 ¥1,000 - ¥2,000：包含知识库刷新 + 模型 prompt 调优。
`,
  },

  {
    slug: "quote-generator",
    name: "报价单一键生成",
    short: "结构化输入（客户 + 项目清单）→ AI 计算 + 套模板 → 输出 PDF / Excel 报价单",
    industry: ["工程", "外贸", "设备制造"],
    complexity: "medium",
    estDays: 5,
    priceCents: [600000, 1200000],
    monthlyCents: [50000, 150000],
    inputs: [
      "客户公司过去 6 个月的报价单样本（≥10 份）",
      "材料 / 服务的标准成本表（Excel）",
      "报价单模板（公司 Logo、版式）",
    ],
    outputs: [
      "Python 命令行工具：录入清单 → 输出 PDF + Excel 报价",
      "AI 报价说明撰写（自动生成「为什么这个价」「附加条款」段落）",
      "客户手册",
    ],
    excludes: [
      "不做和客户对账系统",
      "不替代 ERP 的成本核算（只做报价层）",
    ],
    pricingNote: "工程行业付费意愿强但销售周期偏长；价格波动数据源建议双方约定为客户提供。",
    roi: {
      headline: "单份报价单制作时间从 3-8 小时降至 15 分钟，错报率显著下降",
      formula: "节省工时 ≈ 月报价数 × 节省小时 × ¥150/小时（按工程项目经理时薪估）",
    },
    params: [
      { key: "costTablePath", label: "标准成本表路径", default: "./data/cost-table.xlsx" },
      { key: "templatePath", label: "报价单模板路径", default: "./data/quote-template.xlsx" },
      { key: "currency", label: "货币", default: "CNY" },
      { key: "marginNote", label: "标准毛利率", default: "15%" },
    ],
    pythonTemplate: `${COMMON_PYTHON_HEADER}
import anthropic

COST_PATH = "{{costTablePath}}"
TEMPLATE_PATH = "{{templatePath}}"
CURRENCY = "{{currency}}"
MARGIN_NOTE = "{{marginNote}}"

def main() -> int:
    items = json.load(sys.stdin)
    # 1. lookup cost
    # 2. apply margin
    # 3. ask Claude to draft the "报价说明" paragraph
    client = anthropic.Anthropic()
    explanation = client.messages.create(
        model=os.environ.get("AGENTFLOW_MODEL", "claude-sonnet-4-6"),
        max_tokens=400,
        messages=[{
            "role": "user",
            "content": f"为以下报价撰写一段中文报价说明，包含质量承诺、交期、付款方式、毛利率参考{MARGIN_NOTE}。\\n清单：{json.dumps(items, ensure_ascii=False)}",
        }],
    ).content[0].text  # type: ignore
    print(json.dumps({"explanation": explanation, "items": items, "currency": CURRENCY}, ensure_ascii=False))
    return 0

if __name__ == "__main__":
    sys.exit(main())
`,
    n8nTemplate: {
      name: "AgentFlow - quote-generator",
      nodes: [
        { name: "Webhook In", type: "n8n-nodes-base.webhook", position: [200, 200] },
        { name: "Lookup Cost", type: "n8n-nodes-base.spreadsheetFile", position: [500, 200] },
        { name: "Compose Quote", type: "n8n-nodes-base.httpRequest", parameters: { url: "https://api.anthropic.com/v1/messages" }, position: [800, 200] },
        { name: "Write Excel", type: "n8n-nodes-base.spreadsheetFile", position: [1100, 200] },
      ],
      connections: {
        "Webhook In": { main: [[{ node: "Lookup Cost", type: "main", index: 0 }]] },
        "Lookup Cost": { main: [[{ node: "Compose Quote", type: "main", index: 0 }]] },
        "Compose Quote": { main: [[{ node: "Write Excel", type: "main", index: 0 }]] },
      },
    },
    readmeTemplate: `# 报价单一键生成

> 为 {{clientName}} 定制 · {{generatedAt}}

## 工作流程

1. 收单（webhook / 表单 / 手工 JSON）
2. 查成本表 → 套毛利 → 生成报价金额
3. Claude 撰写「报价说明」段落
4. 写入 Excel 报价单模板

## 部署步骤

\`\`\`bash
pip install anthropic openpyxl
cat sample-items.json | python quote_generator.py > out.json
\`\`\`

## 注意

- 模板和成本表请放到客户私有目录，不上传到本仓库。
- 月度维护建议：成本表月度刷新由客户负责，模型调优由顾问负责。
`,
  },

  {
    slug: "doc-qa-bot",
    name: "企业知识库问答机器人",
    short: "PDF / Word / Excel / 网页 → 向量库 → 聊天界面（飞书 / 企业微信 / 网页）",
    industry: ["通用", "咨询", "律所", "工程"],
    complexity: "medium",
    estDays: 10,
    priceCents: [980000, 3000000],
    monthlyCents: [80000, 200000],
    inputs: [
      "客户的内部文档（建议 50-500 份；过多需先沟通分批）",
      "权限要求（谁能问、谁能看哪类问题）",
      "部署形态：飞书 bot / 企业微信 bot / 独立 Web 页",
    ],
    outputs: [
      "向量库（Chroma 单机或 Qdrant 自托管）",
      "Python 后端 + 简易 Web UI",
      "管理员后台（上传新文档、删除旧文档）",
      "客户使用手册 + 答疑 FAQ",
    ],
    excludes: [
      "不承诺 100% 准确（业务关键问题需人工复核）",
      "不上传客户文档到任何第三方未授权服务",
    ],
    pricingNote: "项目费按文档量与部署复杂度跳档；年维护合同有 ¥10k+ 续费空间。",
    roi: {
      headline: "员工查资料平均节省 30%-50% 时间，新员工上手周期缩短一半",
      formula: "节省工时 ≈ 月问询次数 × 节省分钟 × 60 ÷ 工作小时 × 平均时薪",
    },
    params: [
      { key: "vectorStore", label: "向量库后端", default: "chroma" },
      { key: "embeddingModel", label: "嵌入模型", default: "voyage-3" },
      { key: "deployTarget", label: "部署目标", default: "feishu" },
      { key: "maxFiles", label: "首轮入库文档数上限", default: "300" },
    ],
    pythonTemplate: `${COMMON_PYTHON_HEADER}
import anthropic

VECTOR_STORE = "{{vectorStore}}"
EMBEDDING_MODEL = "{{embeddingModel}}"
DEPLOY_TARGET = "{{deployTarget}}"

def ask(question: str, context_chunks: list[str]) -> str:
    client = anthropic.Anthropic()
    msg = client.messages.create(
        model=os.environ.get("AGENTFLOW_MODEL", "claude-sonnet-4-6"),
        max_tokens=600,
        messages=[
            {"role": "user", "content": "你是企业知识库助手。仅基于下方资料回答，找不到就说\\"资料里没找到\\"。\\n\\n资料：\\n" + "\\n---\\n".join(context_chunks) + "\\n\\n问题：" + question},
        ],
    )
    return msg.content[0].text  # type: ignore

if __name__ == "__main__":
    print("Run with FastAPI / Flask wrapper; see README.")
`,
    n8nTemplate: {
      name: "AgentFlow - doc-qa-bot",
      nodes: [
        { name: "Chat Webhook", type: "n8n-nodes-base.webhook", position: [200, 200] },
        { name: "Vector Search", type: "n8n-nodes-base.httpRequest", parameters: { url: "http://localhost:8000/search" }, position: [500, 200] },
        { name: "Anthropic Answer", type: "n8n-nodes-base.httpRequest", parameters: { url: "https://api.anthropic.com/v1/messages" }, position: [800, 200] },
        { name: "Reply", type: "n8n-nodes-base.respondToWebhook", position: [1100, 200] },
      ],
      connections: {
        "Chat Webhook": { main: [[{ node: "Vector Search", type: "main", index: 0 }]] },
        "Vector Search": { main: [[{ node: "Anthropic Answer", type: "main", index: 0 }]] },
        "Anthropic Answer": { main: [[{ node: "Reply", type: "main", index: 0 }]] },
      },
    },
    readmeTemplate: `# 企业知识库问答机器人

> 为 {{clientName}} 部署 · {{generatedAt}}

部署形态：**{{deployTarget}}**。向量库后端：**{{vectorStore}}**。嵌入模型：**{{embeddingModel}}**。

## 部署步骤

1. \`pip install anthropic chromadb fastapi uvicorn\`
2. 把客户文档放到 \`./docs/\`，运行 \`python ingest.py\` 构建向量库。
3. 运行 \`uvicorn server:app --port 8000\`。
4. 在飞书 / 企业微信里配置 bot Webhook 指向 \`http://your-host:8000/chat\`。

## 限制声明

机器人只回答**入库文档里有的**内容；超出范围会主动说"资料里没找到"。重要业务问题请人工复核。

## 更新文档

- 客户：把新文档放到 \`./docs/\`，跑 \`python ingest.py --update\`。
- 顾问：月度维护合同包含每月 1 次知识库重建与 prompt 调优。
`,
  },

  {
    slug: "excel-batch",
    name: "Excel 智能批处理",
    short: "上传一堆 Excel → AI 理解结构 → 清洗 / 汇总 / 提取 → 输出标准报表",
    industry: ["财务", "运营", "供应链"],
    complexity: "simple",
    estDays: 3,
    priceCents: [198000, 500000],
    monthlyCents: [30000, 80000],
    inputs: [
      "样本 Excel 文件（3-5 份代表性的）",
      "目标输出格式（一份示例 Excel）",
      "处理规则（哪些列要合并、哪些要去重、哪些要按月汇总）",
    ],
    outputs: [
      "Python 脚本 + requirements.txt",
      "运行说明",
      "可选：拖拽上传 Web 界面",
    ],
    excludes: [
      "不接管客户已有 Excel 宏（除非客户主动让顾问 review）",
      "不做 BI / 可视化（如客户需要，请单独走 dashboard 模板）",
    ],
    pricingNote: "复杂度最低的入门型项目；适合作为新客户首单。",
    roi: {
      headline: "原来每周 4-6 小时手动汇总，现在 5 分钟完成",
      formula: "节省工时 = 月任务次数 × 节省小时 × 平均时薪",
    },
    params: [
      { key: "inputDir", label: "输入目录", default: "./in" },
      { key: "outputPath", label: "输出文件", default: "./out/汇总.xlsx" },
      { key: "rules", label: "规则简述", multiline: true, default: "1. 合并所有 sheet\\n2. 按月汇总\\n3. 去重订单号" },
    ],
    pythonTemplate: `${COMMON_PYTHON_HEADER}
import pandas as pd
from pathlib import Path

INPUT_DIR = Path("{{inputDir}}")
OUTPUT_PATH = Path("{{outputPath}}")
RULES = """{{rules}}"""

def main() -> int:
    dfs = []
    for f in INPUT_DIR.glob("*.xlsx"):
        dfs.append(pd.read_excel(f))
    if not dfs:
        print("no excel files found in", INPUT_DIR, file=sys.stderr)
        return 1
    df = pd.concat(dfs, ignore_index=True)
    # apply project-specific transforms here
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    df.to_excel(OUTPUT_PATH, index=False)
    print(f"wrote {len(df)} rows → {OUTPUT_PATH}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
`,
    n8nTemplate: {
      name: "AgentFlow - excel-batch",
      nodes: [
        { name: "Cron", type: "n8n-nodes-base.cron", position: [200, 200] },
        { name: "Read Files", type: "n8n-nodes-base.readBinaryFiles", position: [500, 200] },
        { name: "Merge", type: "n8n-nodes-base.merge", position: [800, 200] },
        { name: "Write Excel", type: "n8n-nodes-base.spreadsheetFile", position: [1100, 200] },
      ],
      connections: {
        Cron: { main: [[{ node: "Read Files", type: "main", index: 0 }]] },
        "Read Files": { main: [[{ node: "Merge", type: "main", index: 0 }]] },
        Merge: { main: [[{ node: "Write Excel", type: "main", index: 0 }]] },
      },
    },
    readmeTemplate: `# Excel 智能批处理

> 为 {{clientName}} 定制 · {{generatedAt}}

把多份 Excel 自动合并 / 清洗 / 汇总成一份标准报表。

## 运行

\`\`\`bash
pip install pandas openpyxl
python excel_batch.py
\`\`\`

输入文件放在 \`{{inputDir}}\`，输出为 \`{{outputPath}}\`。

## 限制

- 仅支持 \`.xlsx\`（如有 \`.xls\` 请先转换）。
- 单文件大小 < 50MB 测试通过；更大文件请走专门方案。

## 处理规则

{{rules}}
`,
  },

  {
    slug: "customer-service",
    name: "客服问题自动分类与回复",
    short: "微信 / 钉钉 / 客服系统消息 → AI 分类 → 匹配 FAQ 知识库 → 草拟回复 → 人工确认",
    industry: ["电商", "本地服务", "SaaS"],
    complexity: "medium",
    estDays: 7,
    priceCents: [600000, 1200000],
    monthlyCents: [80000, 150000],
    inputs: [
      "近 30 天历史客服对话（脱敏后）≥200 条",
      "现有 FAQ / 知识库",
      "客服系统接入凭证",
    ],
    outputs: [
      "分类模型（小型 prompt 即可，无需训练）",
      "FAQ 向量库",
      "回复草拟脚本",
      "客服培训手册 + 准确率监控表",
    ],
    excludes: [
      "不直接发回复给客户（首期都需人工审核）",
      "不接管投诉处理（涉及退款等敏感场景）",
    ],
    pricingNote: "电商客户付费意愿强；上线后 1-2 周建议主动跟客户对账准确率。",
    roi: {
      headline: "客服平均响应时间 -60%，单人日处理消息数 +100%",
      formula: "净收益 = 客服人数 × 节省小时 × 时薪",
    },
    params: [
      { key: "channels", label: "接入渠道", default: "wechat-work,dingtalk" },
      { key: "categories", label: "问题分类", default: "售前咨询,物流查询,退换货,价格,其他" },
      { key: "autoReplyThreshold", label: "自动发送阈值（0-1）", default: "0.0" },
    ],
    pythonTemplate: `${COMMON_PYTHON_HEADER}
import anthropic

CHANNELS = "{{channels}}".split(",")
CATEGORIES = "{{categories}}".split(",")
AUTO_REPLY_THRESHOLD = float("{{autoReplyThreshold}}")

def classify_and_draft(msg: str) -> Dict[str, Any]:
    client = anthropic.Anthropic()
    resp = client.messages.create(
        model=os.environ.get("AGENTFLOW_MODEL", "claude-sonnet-4-6"),
        max_tokens=500,
        messages=[{"role": "user", "content": f"分类与起草回复。\\n问题分类候选：{CATEGORIES}\\n用 JSON 输出 {{\\"category\\":..., \\"confidence\\":0-1, \\"draft_reply\\":...}}。\\n\\n用户消息：{msg}"}],
    )
    text = resp.content[0].text  # type: ignore
    start, end = text.find("{"), text.rfind("}")
    return json.loads(text[start:end+1])

if __name__ == "__main__":
    msg = sys.stdin.read()
    out = classify_and_draft(msg)
    if out.get("confidence", 0) >= AUTO_REPLY_THRESHOLD and AUTO_REPLY_THRESHOLD > 0:
        out["mode"] = "auto"
    else:
        out["mode"] = "draft-for-human"
    print(json.dumps(out, ensure_ascii=False, indent=2))
`,
    n8nTemplate: {
      name: "AgentFlow - customer-service",
      nodes: [
        { name: "WeWork Webhook", type: "n8n-nodes-base.webhook", position: [200, 200] },
        { name: "Classify+Draft", type: "n8n-nodes-base.httpRequest", parameters: { url: "https://api.anthropic.com/v1/messages" }, position: [500, 200] },
        { name: "If High Confidence", type: "n8n-nodes-base.if", position: [800, 200] },
        { name: "Send Reply", type: "n8n-nodes-base.httpRequest", position: [1100, 100] },
        { name: "Notify Human", type: "n8n-nodes-base.httpRequest", position: [1100, 300] },
      ],
      connections: {
        "WeWork Webhook": { main: [[{ node: "Classify+Draft", type: "main", index: 0 }]] },
        "Classify+Draft": { main: [[{ node: "If High Confidence", type: "main", index: 0 }]] },
        "If High Confidence": {
          main: [
            [{ node: "Send Reply", type: "main", index: 0 }],
            [{ node: "Notify Human", type: "main", index: 0 }],
          ],
        },
      },
    },
    readmeTemplate: `# 客服问题自动分类与回复

> 为 {{clientName}} 定制 · {{generatedAt}}

## 工作模式

1. 客服系统转发消息到 webhook。
2. 模型分类（{{categories}}）+ 起草回复。
3. 高置信度 → 自动发送（阈值 {{autoReplyThreshold}}，建议第一个月保持 0 即"全部人工审核"）。
4. 低置信度 → 进人工队列。

## 上线建议

- 第 1-2 周保持 100% 人工审核。
- 每周对照模型分类 vs 实际分类，<90% 准确率则重新调优。
- 高风险问题（投诉、退款）建议永远走人工。
`,
  },

  {
    slug: "price-monitor",
    name: "工程材料价格监控",
    short: "每日抓取 N 个材料价格源 → AI 异常识别 → 写入价格表 + 报警",
    industry: ["工程", "制造", "建材"],
    complexity: "medium",
    estDays: 7,
    priceCents: [800000, 1800000],
    monthlyCents: [80000, 200000],
    inputs: [
      "客户关注的材料清单（钢材、电缆、防水材料等）",
      "客户认可的价格数据源（造价信息站、上海钢联等）",
      "异常阈值（如日波动 > 3% 即报警）",
    ],
    outputs: [
      "Python 抓取脚本 + 定时任务（cron / Airflow）",
      "历史价格表（SQLite 或 Excel）",
      "钉钉 / 企业微信报警机器人配置",
    ],
    excludes: [
      "不绕过任何反爬保护；客户需自己签订数据源访问授权",
      "不替代采购决策；只提供数据 + 报警",
    ],
    pricingNote: "数据源合规是最大风险，签合同前务必和客户确认数据访问授权。",
    roi: {
      headline: "材料采购报价误差从 ±10% 降到 ±2%，避免一次错报损失 5-50 万",
      formula: "ROI = 单项目报价金额 × 误差降低比例（按 5% 估）",
    },
    params: [
      { key: "materials", label: "监控材料", default: "螺纹钢,电缆,水泥,沥青" },
      { key: "alertChannel", label: "报警 Webhook", default: "https://oapi.dingtalk.com/robot/send?access_token=XXX" },
      { key: "threshold", label: "波动阈值", default: "3%" },
    ],
    pythonTemplate: `${COMMON_PYTHON_HEADER}
import os
import sqlite3
import urllib.request

MATERIALS = "{{materials}}".split(",")
ALERT_WEBHOOK = "{{alertChannel}}"
THRESHOLD_PCT = float("{{threshold}}".strip("%")) / 100.0
DATA_SOURCE_URL = os.environ.get("PRICE_DATA_SOURCE", "")  # 客户授权的数据源 base URL
DB_PATH = os.environ.get("PRICE_DB", "prices.db")

def _init_db() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH)
    conn.execute("CREATE TABLE IF NOT EXISTS prices (material TEXT, price REAL, fetched_at TEXT)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_prices_mat_at ON prices(material, fetched_at)")
    conn.commit()
    return conn

def fetch_price(material: str) -> float:
    """从客户授权数据源拉取最新报价。PRICE_DATA_SOURCE 未配置时回退到 stub（仅供 demo）。
    生产环境应根据数据源协议改写（如造价信息站 token / 上海钢联 API / 自建抓取代理）。"""
    if not DATA_SOURCE_URL:
        return 0.0
    url = f"{DATA_SOURCE_URL}?material={urllib.parse.quote(material)}"
    with urllib.request.urlopen(url, timeout=10) as r:
        data = json.loads(r.read().decode("utf-8"))
    return float(data.get("price", 0.0))

def last_price(conn: sqlite3.Connection, material: str) -> Optional[float]:
    row = conn.execute("SELECT price FROM prices WHERE material=? ORDER BY fetched_at DESC LIMIT 1", (material,)).fetchone()
    return row[0] if row else None

def alert(material: str, prev: float, curr: float) -> None:
    pct = (curr - prev) / prev * 100 if prev else 0
    body = json.dumps({"msgtype": "text", "text": {"content": f"⚠️ {material} 价格波动 {pct:+.1f}%（{prev} → {curr}）"}}).encode("utf-8")
    req = urllib.request.Request(ALERT_WEBHOOK, data=body, headers={"Content-Type": "application/json"})
    try:
        urllib.request.urlopen(req, timeout=5)
    except Exception as e:
        print(f"[alert] FAILED for {material}: {e}", file=sys.stderr)

def main() -> int:
    conn = _init_db()
    rows = []
    for m in MATERIALS:
        m = m.strip()
        if not m:
            continue
        try:
            curr = fetch_price(m)
        except Exception as e:
            print(f"[fetch] FAILED {m}: {e}", file=sys.stderr)
            continue
        prev = last_price(conn, m)
        conn.execute("INSERT INTO prices VALUES (?, ?, datetime('now'))", (m, curr))
        if prev and prev > 0 and abs(curr - prev) / prev >= THRESHOLD_PCT:
            alert(m, prev, curr)
        rows.append({"material": m, "price": curr, "prev": prev})
    conn.commit()
    print(json.dumps(rows, ensure_ascii=False))
    return 0

if __name__ == "__main__":
    sys.exit(main())
`,
    n8nTemplate: {
      name: "AgentFlow - price-monitor",
      nodes: [
        { name: "Cron Daily", type: "n8n-nodes-base.cron", position: [200, 200] },
        { name: "Fetch Source A", type: "n8n-nodes-base.httpRequest", position: [500, 100] },
        { name: "Fetch Source B", type: "n8n-nodes-base.httpRequest", position: [500, 300] },
        { name: "Merge + Detect", type: "n8n-nodes-base.functionItem", position: [800, 200] },
        { name: "Alert", type: "n8n-nodes-base.httpRequest", parameters: { url: "{{alertChannel}}" }, position: [1100, 200] },
      ],
      connections: {
        "Cron Daily": {
          main: [
            [{ node: "Fetch Source A", type: "main", index: 0 }],
            [{ node: "Fetch Source B", type: "main", index: 0 }],
          ],
        },
        "Fetch Source A": { main: [[{ node: "Merge + Detect", type: "main", index: 0 }]] },
        "Fetch Source B": { main: [[{ node: "Merge + Detect", type: "main", index: 0 }]] },
        "Merge + Detect": { main: [[{ node: "Alert", type: "main", index: 0 }]] },
      },
    },
    readmeTemplate: `# 工程材料价格监控

> 为 {{clientName}} 定制 · {{generatedAt}}

每天定时抓取材料价格 → 异常报警 → 入历史表。

## 重要

数据源访问授权由客户负责。请勿绕开反爬保护。

## 部署

\`\`\`bash
# 安装 cron 或用 systemd timer
crontab -e
# 每天早 8 点跑
0 8 * * * cd /opt/agent-flow && /usr/bin/python3 price_monitor.py
\`\`\`

## 配置

- 监控材料：{{materials}}
- 异常阈值：{{threshold}}
- 报警 Webhook：{{alertChannel}}
`,
  },

  {
    slug: "hr-onboarding",
    name: "员工入职流程自动化",
    short: "入职申请 → AI 核对资料完整性 → 多系统账号开通 → 入职任务派发 → 进度看板",
    industry: ["通用", "科技", "服务业", "制造"],
    complexity: "medium",
    estDays: 7,
    priceCents: [800000, 1500000],
    monthlyCents: [80000, 150000],
    inputs: [
      "现有入职 checklist 模板 + 上一年度 5-10 份历史案例",
      "需开通的系统清单（钉钉/企业微信、邮箱、OA、专用工具账号），及对应管理员/接口",
      "IT/行政/财务的责任人对应表",
      "新员工首日所需材料（合同、保密、应聘登记等）",
    ],
    outputs: [
      "Python 主控脚本（资料校验 + 任务派发 + 进度跟踪）",
      "n8n 工作流（钉钉/企业微信审批触发 → 多分支动作）",
      "HR 操作手册 + 例外处理 SOP",
    ],
    excludes: [
      "不接管劳动合同电子签（建议对接法大大 / e 签宝）",
      "不直接开通需人工审核的特权账号（如生产系统）",
      "不替代 HRBP 与员工的入职沟通",
    ],
    pricingNote: "复杂度由接入系统数决定：≤3 套系统走低端；>5 套或需自定义审批走中高端。",
    roi: {
      headline: "HR 单次入职操作 4-6 小时 → 30 分钟；漏掉账号导致的首日空转下降 90%",
      formula: "ROI = 每月入职人数 × 节省 4 小时 × HR 时薪 + 减少首日空转的隐性成本",
    },
    params: [
      { key: "systems", label: "需开通系统（逗号分隔）", default: "钉钉,企业邮箱,OA,工时系统" },
      { key: "approver", label: "审批人钉钉/企微 ID", default: "hr_lead" },
      { key: "checklistUrl", label: "checklist 模板 URL", default: "https://example.com/hr/checklist.json" },
      { key: "alertWebhook", label: "异常告警 Webhook", default: "https://oapi.dingtalk.com/robot/send?access_token=XXX" },
    ],
    pythonTemplate: `${COMMON_PYTHON_HEADER}
import urllib.request
import anthropic

SYSTEMS = "{{systems}}".split(",")
APPROVER = "{{approver}}"
CHECKLIST_URL = "{{checklistUrl}}"
ALERT_WEBHOOK = "{{alertWebhook}}"

VALIDATE_PROMPT = (
    "你是 HR 入职助手。检查下面候选人的入职资料是否完整。"
    "必备字段：姓名、身份证号、入职日期、岗位、紧急联系人、银行卡号。"
    "缺哪些就用 JSON 列出 missing 数组；都齐则 missing 为空。"
)

def load_checklist() -> List[Dict[str, Any]]:
    with urllib.request.urlopen(CHECKLIST_URL, timeout=10) as r:
        return json.loads(r.read().decode("utf-8"))

def validate(applicant: Dict[str, Any]) -> List[str]:
    client = anthropic.Anthropic()
    msg = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=400,
        messages=[{"role": "user", "content": VALIDATE_PROMPT + "\\n\\n资料：\\n" + json.dumps(applicant, ensure_ascii=False)}],
    )
    text = msg.content[0].text  # type: ignore
    start, end = text.find("{"), text.rfind("}")
    return json.loads(text[start:end + 1]).get("missing", []) if start >= 0 else []

def provision(applicant: Dict[str, Any]) -> List[Dict[str, Any]]:
    """逐个系统下发开通工单。集成方式按客户实际系统改写。"""
    out = []
    for sys_name in SYSTEMS:
        sys_name = sys_name.strip()
        if not sys_name:
            continue
        # Stub: 真实集成时按目标 API 重写。这里仅记录待办。
        out.append({"system": sys_name, "applicant": applicant.get("name"), "status": "queued"})
    return out

def notify(payload: Dict[str, Any]) -> None:
    body = json.dumps({"msgtype": "text", "text": {"content": json.dumps(payload, ensure_ascii=False)}}).encode("utf-8")
    req = urllib.request.Request(ALERT_WEBHOOK, data=body, headers={"Content-Type": "application/json"})
    urllib.request.urlopen(req, timeout=5)

def main() -> int:
    applicant = json.loads(sys.stdin.read())
    missing = validate(applicant)
    if missing:
        notify({"applicant": applicant.get("name"), "stage": "blocked", "missing": missing, "approver": APPROVER})
        print(json.dumps({"status": "blocked", "missing": missing}, ensure_ascii=False))
        return 1
    tasks = provision(applicant)
    notify({"applicant": applicant.get("name"), "stage": "provisioned", "tasks": tasks})
    print(json.dumps({"status": "ok", "tasks": tasks}, ensure_ascii=False, indent=2))
    return 0

if __name__ == "__main__":
    sys.exit(main())
`,
    n8nTemplate: {
      name: "AgentFlow - hr-onboarding",
      nodes: [
        { name: "DingTalk Approval Trigger", type: "n8n-nodes-base.webhook", parameters: { path: "hr-onboarding" }, position: [200, 200] },
        { name: "AI Validate", type: "n8n-nodes-base.httpRequest", parameters: { url: "https://api.anthropic.com/v1/messages" }, position: [500, 200] },
        { name: "Has Missing?", type: "n8n-nodes-base.if", position: [800, 200] },
        { name: "Provision Accounts", type: "n8n-nodes-base.httpRequest", position: [1100, 100] },
        { name: "Notify HR", type: "n8n-nodes-base.httpRequest", position: [1100, 300] },
      ],
      connections: {
        "DingTalk Approval Trigger": { main: [[{ node: "AI Validate", type: "main", index: 0 }]] },
        "AI Validate": { main: [[{ node: "Has Missing?", type: "main", index: 0 }]] },
        "Has Missing?": {
          main: [
            [{ node: "Notify HR", type: "main", index: 0 }],
            [{ node: "Provision Accounts", type: "main", index: 0 }],
          ],
        },
      },
    },
    readmeTemplate: `# 员工入职流程自动化

> 为 {{clientName}} 定制 · {{generatedAt}}

## 工作模式

1. HRBP 在钉钉/企微提交入职审批（候选人 JSON）。
2. AI 核对资料完整性，缺字段 → 退回 HR 补；齐全 → 进入开通。
3. 系统按 {{systems}} 列表逐项下发开通工单。
4. 完成后推送 {{approver}} 入职清单。

## 上线建议

- 第 1 周建议「开通工单生成」与「实际下发」分离，HR 人工 confirm 后再下发。
- 第 2 周接入审批通过即自动下发。
- 高风险系统（财务/生产）永远走人工。
`,
  },

  {
    slug: "finance-reconciliation",
    name: "银行流水多源对账",
    short: "银行 CSV + 内部账单 → AI 模糊匹配（金额+时间+对方+摘要）→ 差异表 → 财务复核",
    industry: ["财务", "电商", "服务业", "供应链"],
    complexity: "medium",
    estDays: 7,
    priceCents: [600000, 1200000],
    monthlyCents: [80000, 150000],
    inputs: [
      "银行流水样本（≥3 个月，每月 ≥100 条）",
      "内部账单样本（订单系统 / ERP 导出 / 手工台账）",
      "对账规则（按金额/订单号/客户名/备注等的匹配优先级）",
    ],
    outputs: [
      "Python 对账脚本（fuzzy 匹配 + 报告生成 Excel）",
      "n8n 定时工作流（每日凌晨拉两边流水 → 出对账报告）",
      "财务复核手册 + 异常 case 库",
    ],
    excludes: [
      "不直接调整账务（仅出差异报告供财务人工核销）",
      "不替代税务系统接口；只做内部对账",
      "不承诺 100% 自动匹配；目标 80%+ 自动 + 20% 人工",
    ],
    pricingNote: "数据 schema 差异是工作量大头。电商订单清晰的客户 6 万就够；线下混合账客户得 10 万起。",
    roi: {
      headline: "财务月底对账从 3-5 天压缩到 4-8 小时；漏账 / 错账金额下降 80%",
      formula: "ROI = 财务人天节省 + 漏账金额 × 发现概率提升",
    },
    params: [
      { key: "bankCsvPath", label: "银行流水 CSV 路径", default: "./input/bank_statement.csv" },
      { key: "ledgerCsvPath", label: "内部账单 CSV 路径", default: "./input/internal_ledger.csv" },
      { key: "outputDir", label: "对账结果输出目录", default: "./output" },
      { key: "amountToleranceCents", label: "金额容差（分）", default: "100" },
    ],
    pythonTemplate: `${COMMON_PYTHON_HEADER}
import csv
import datetime as dt
from pathlib import Path
import anthropic

BANK_CSV = Path("{{bankCsvPath}}")
LEDGER_CSV = Path("{{ledgerCsvPath}}")
OUTPUT_DIR = Path("{{outputDir}}")
TOLERANCE_CENTS = int("{{amountToleranceCents}}")

def load_csv(path: Path) -> List[Dict[str, Any]]:
    with path.open(encoding="utf-8") as f:
        return list(csv.DictReader(f))

def to_cents(amount: str) -> int:
    return round(float(str(amount).replace(",", "").strip() or 0) * 100)

def match_rule_based(bank: List[Dict[str, Any]], ledger: List[Dict[str, Any]]) -> Dict[str, List[Dict[str, Any]]]:
    """精确匹配：金额相等（容差内）且日期相邻 ≤ 2 天。"""
    matched, unmatched_bank, unmatched_ledger = [], [], []
    used = set()
    for b in bank:
        b_amt = to_cents(b.get("金额") or b.get("amount") or 0)
        b_date = b.get("日期") or b.get("date") or ""
        hit = None
        for i, l in enumerate(ledger):
            if i in used:
                continue
            l_amt = to_cents(l.get("金额") or l.get("amount") or 0)
            if abs(b_amt - l_amt) > TOLERANCE_CENTS:
                continue
            l_date = l.get("日期") or l.get("date") or ""
            if abs((_parse(b_date) - _parse(l_date)).days) <= 2:
                hit = (i, l)
                break
        if hit:
            used.add(hit[0])
            matched.append({"bank": b, "ledger": hit[1], "method": "rule"})
        else:
            unmatched_bank.append(b)
    for i, l in enumerate(ledger):
        if i not in used:
            unmatched_ledger.append(l)
    return {"matched": matched, "unmatched_bank": unmatched_bank, "unmatched_ledger": unmatched_ledger}

def _parse(s: str) -> dt.date:
    for fmt in ("%Y-%m-%d", "%Y/%m/%d", "%d/%m/%Y", "%m/%d/%Y"):
        try:
            return dt.datetime.strptime(s.strip()[:10], fmt).date()
        except Exception:
            continue
    return dt.date(1900, 1, 1)

def ai_match_remaining(unmatched_bank: List[Dict[str, Any]], unmatched_ledger: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """剩余条目交给 LLM 做模糊（金额接近 / 摘要语义 / 对方名相似）配对。"""
    if not unmatched_bank or not unmatched_ledger:
        return []
    client = anthropic.Anthropic()
    prompt = (
        "下面是银行流水里没匹配上的条目和内部账单里没匹配上的条目，"
        "请基于金额接近、对方名相似、摘要语义找出可能成对的条目。"
        "用 JSON 数组返回：[{bank_idx, ledger_idx, confidence: 0-1, reason}]。confidence < 0.6 不要返回。"
    )
    payload = json.dumps({"bank": unmatched_bank[:30], "ledger": unmatched_ledger[:30]}, ensure_ascii=False)
    msg = client.messages.create(model="claude-sonnet-4-6", max_tokens=1200, messages=[{"role": "user", "content": prompt + "\\n\\n" + payload}])
    text = msg.content[0].text  # type: ignore
    start, end = text.find("["), text.rfind("]")
    return json.loads(text[start:end + 1]) if start >= 0 else []

def write_report(result: Dict[str, Any]) -> Path:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    out = OUTPUT_DIR / f"recon-{dt.date.today().isoformat()}.json"
    out.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    return out

def main() -> int:
    bank = load_csv(BANK_CSV)
    ledger = load_csv(LEDGER_CSV)
    rule = match_rule_based(bank, ledger)
    ai = ai_match_remaining(rule["unmatched_bank"], rule["unmatched_ledger"])
    path = write_report({"summary": {"matched_rule": len(rule["matched"]), "matched_ai": len(ai), "unmatched_bank": len(rule["unmatched_bank"]) - len(ai), "unmatched_ledger": len(rule["unmatched_ledger"]) - len(ai)}, "rule_matches": rule["matched"], "ai_matches": ai, "unmatched_bank": rule["unmatched_bank"], "unmatched_ledger": rule["unmatched_ledger"]})
    print(f"[recon] report → {path}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
`,
    n8nTemplate: {
      name: "AgentFlow - finance-reconciliation",
      nodes: [
        { name: "Cron Nightly", type: "n8n-nodes-base.cron", position: [200, 200] },
        { name: "Fetch Bank CSV", type: "n8n-nodes-base.httpRequest", position: [500, 100] },
        { name: "Fetch Ledger CSV", type: "n8n-nodes-base.httpRequest", position: [500, 300] },
        { name: "Run Recon Script", type: "n8n-nodes-base.executeCommand", position: [800, 200] },
        { name: "Email Report", type: "n8n-nodes-base.emailSend", position: [1100, 200] },
      ],
      connections: {
        "Cron Nightly": {
          main: [
            [{ node: "Fetch Bank CSV", type: "main", index: 0 }],
            [{ node: "Fetch Ledger CSV", type: "main", index: 0 }],
          ],
        },
        "Fetch Bank CSV": { main: [[{ node: "Run Recon Script", type: "main", index: 0 }]] },
        "Fetch Ledger CSV": { main: [[{ node: "Run Recon Script", type: "main", index: 0 }]] },
        "Run Recon Script": { main: [[{ node: "Email Report", type: "main", index: 0 }]] },
      },
    },
    readmeTemplate: `# 银行流水多源对账

> 为 {{clientName}} 定制 · {{generatedAt}}

## 工作模式

1. 每天凌晨拉一次银行流水与内部账单（CSV）。
2. 规则匹配（金额容差 ≤ {{amountToleranceCents}} 分 + 日期 ±2 天）。
3. 剩余项交给 LLM 做模糊匹配（置信度 ≥0.6 才记入 ai_matches）。
4. 输出 JSON 报告到 {{outputDir}}，邮件发送给财务。

## 上线建议

- 第 1 周用样本数据跑回测，统计自动匹配率。<70% 时调整匹配规则。
- 财务对照规则匹配（高置信）+ AI 匹配（中置信）+ 未匹配（低置信），分组复核。
- 持续把"被人工修正的 ai_matches"做成 prompt 例子，迭代提示词。
`,
  },

  {
    slug: "ecommerce-order-routing",
    name: "多平台订单聚合分发",
    short: "淘宝/抖音/拼多多/微店 → 统一订单格式 → 库存校验 → 仓库分仓 → 物流推送",
    industry: ["电商", "新零售"],
    complexity: "complex",
    estDays: 14,
    priceCents: [1500000, 4000000],
    monthlyCents: [150000, 400000],
    inputs: [
      "客户已对接的平台清单 + 对应商家中心账号（或 API 凭证）",
      "现有仓库清单 + 各仓 SKU 库存源（Excel 或 WMS API）",
      "分仓规则（按地区 / 按 SKU / 按平台优先级）",
      "物流商对应表（顺丰 / 京东 / 通达系 API key 或电子面单平台）",
    ],
    outputs: [
      "Python 订单聚合服务（4 平台 webhook / 拉单脚本 + 统一订单 schema）",
      "n8n 工作流（订单进库 → 校验 → 路由 → 出物流单号）",
      "运营手册 + 异常订单 SOP（断货 / 地址异常 / 加急）",
    ],
    excludes: [
      "不直接修改平台后台订单状态（避免触发风控）；仅做出库回写",
      "不处理售后退款流程（建议另立模板）",
      "不替代 WMS / OMS；若客户无 WMS 建议先小规模试运行",
    ],
    pricingNote: "平台数量 × 仓库数量决定接口工作量。3 平台 1 仓走 1.5 万；4+ 平台多仓走 3-4 万。",
    roi: {
      headline: "订单处理 1-2 min → 5 sec，发货错误率从 3% 降到 <0.5%",
      formula: "ROI = 日均订单量 × 节省每单时间 + 错发率下降带来的退货成本节省",
    },
    params: [
      { key: "platforms", label: "接入平台（逗号分隔）", default: "taobao,douyin,pdd,weidian" },
      { key: "warehouses", label: "仓库列表（逗号分隔）", default: "GZ-HQ,SH-NORTH,CD-WEST" },
      { key: "routingRule", label: "分仓规则", default: "region" },
      { key: "logisticsWebhook", label: "电子面单平台 API", default: "https://api.kdniao.com/api/eorderservice" },
    ],
    pythonTemplate: `${COMMON_PYTHON_HEADER}
import urllib.request

PLATFORMS = "{{platforms}}".split(",")
WAREHOUSES = "{{warehouses}}".split(",")
ROUTING_RULE = "{{routingRule}}"
LOGISTICS_WEBHOOK = "{{logisticsWebhook}}"

# 简化的统一订单 schema；真实集成应使用 Pydantic 校验。
UnifiedOrder = Dict[str, Any]

def fetch_orders(platform: str) -> List[UnifiedOrder]:
    """拉取该平台未发货订单。各平台 API 不同，需逐个实现 _fetch_<platform>()。"""
    fn = globals().get(f"_fetch_{platform}")
    if not fn:
        print(f"[fetch] no fetcher for {platform}", file=sys.stderr)
        return []
    return fn()

def _fetch_taobao() -> List[UnifiedOrder]:
    # 真实接入：调用淘宝开放平台 taobao.trades.sold.get
    return []

def _fetch_douyin() -> List[UnifiedOrder]:
    return []

def _fetch_pdd() -> List[UnifiedOrder]:
    return []

def _fetch_weidian() -> List[UnifiedOrder]:
    return []

def check_stock(order: UnifiedOrder, warehouse: str) -> bool:
    """库存校验。真实集成应调 WMS API；本 stub 默认 True。"""
    return True

def route(order: UnifiedOrder) -> str:
    if ROUTING_RULE == "region":
        # 简单按收货省份匹配；真实业务用 ProvinceCode → WarehouseCode 映射表。
        prov = order.get("province", "")
        if prov.startswith("广") or prov.startswith("海"):
            return WAREHOUSES[0]
        if prov.startswith("上") or prov.startswith("江") or prov.startswith("浙"):
            return WAREHOUSES[1] if len(WAREHOUSES) > 1 else WAREHOUSES[0]
        return WAREHOUSES[-1]
    if ROUTING_RULE == "platform":
        return WAREHOUSES[hash(order.get("platform", "")) % len(WAREHOUSES)]
    return WAREHOUSES[0]

def request_waybill(order: UnifiedOrder, warehouse: str) -> Optional[str]:
    """向电子面单平台申请运单号。失败返回 None，由调用方决定是否重试。"""
    payload = {"order_id": order.get("order_id"), "warehouse": warehouse, "to": order.get("address")}
    body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(LOGISTICS_WEBHOOK, data=body, headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=10) as r:
            data = json.loads(r.read().decode("utf-8"))
            return data.get("waybill_no")
    except Exception as e:
        print(f"[waybill] FAILED {order.get('order_id')}: {e}", file=sys.stderr)
        return None

def main() -> int:
    summary = {"fetched": 0, "routed": 0, "out_of_stock": 0, "waybill_failed": 0}
    for p in PLATFORMS:
        orders = fetch_orders(p.strip())
        summary["fetched"] += len(orders)
        for o in orders:
            wh = route(o)
            if not check_stock(o, wh):
                summary["out_of_stock"] += 1
                continue
            wb = request_waybill(o, wh)
            if wb:
                summary["routed"] += 1
            else:
                summary["waybill_failed"] += 1
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0

if __name__ == "__main__":
    sys.exit(main())
`,
    n8nTemplate: {
      name: "AgentFlow - ecommerce-order-routing",
      nodes: [
        { name: "Cron 5min", type: "n8n-nodes-base.cron", position: [200, 200] },
        { name: "Pull Taobao", type: "n8n-nodes-base.httpRequest", position: [500, 50] },
        { name: "Pull Douyin", type: "n8n-nodes-base.httpRequest", position: [500, 150] },
        { name: "Pull PDD", type: "n8n-nodes-base.httpRequest", position: [500, 250] },
        { name: "Pull Weidian", type: "n8n-nodes-base.httpRequest", position: [500, 350] },
        { name: "Merge + Normalize", type: "n8n-nodes-base.functionItem", position: [800, 200] },
        { name: "Stock + Route", type: "n8n-nodes-base.functionItem", position: [1100, 200] },
        { name: "Request Waybill", type: "n8n-nodes-base.httpRequest", parameters: { url: "{{logisticsWebhook}}" }, position: [1400, 200] },
      ],
      connections: {
        "Cron 5min": {
          main: [
            [{ node: "Pull Taobao", type: "main", index: 0 }],
            [{ node: "Pull Douyin", type: "main", index: 0 }],
            [{ node: "Pull PDD", type: "main", index: 0 }],
            [{ node: "Pull Weidian", type: "main", index: 0 }],
          ],
        },
        "Pull Taobao": { main: [[{ node: "Merge + Normalize", type: "main", index: 0 }]] },
        "Pull Douyin": { main: [[{ node: "Merge + Normalize", type: "main", index: 0 }]] },
        "Pull PDD": { main: [[{ node: "Merge + Normalize", type: "main", index: 0 }]] },
        "Pull Weidian": { main: [[{ node: "Merge + Normalize", type: "main", index: 0 }]] },
        "Merge + Normalize": { main: [[{ node: "Stock + Route", type: "main", index: 0 }]] },
        "Stock + Route": { main: [[{ node: "Request Waybill", type: "main", index: 0 }]] },
      },
    },
    readmeTemplate: `# 多平台订单聚合分发

> 为 {{clientName}} 定制 · {{generatedAt}}

## 工作模式

1. 每 5 分钟轮询 {{platforms}} 平台未发货订单。
2. 归一到统一 schema，校验库存（{{warehouses}}）。
3. 按 {{routingRule}} 规则分仓。
4. 调电子面单平台获取运单号，回写各平台后台。

## 上线建议

- 第 1 周仅做"拉单 + 归一 + 路由建议"，不写回平台。运营人工 confirm。
- 第 2 周开启自动写回，但保留 30 分钟撤回窗口。
- 加急 / VIP 订单永远走人工。
- 平台风控敏感，建议每个平台账号每分钟 API 调用 < 10 次。
`,
  },
];

export const TEMPLATE_BY_SLUG: Record<string, Template> = Object.fromEntries(TEMPLATES.map((t) => [t.slug, t]));

export function getTemplate(slug: string): Template | undefined {
  return TEMPLATE_BY_SLUG[slug];
}

export function templateSummary(t: Template): string {
  return `${t.name} (${t.slug}) · ${t.complexity} · ${t.estDays}d · ¥${(t.priceCents[0] / 100).toLocaleString()}-${(t.priceCents[1] / 100).toLocaleString()} · ${t.short}`;
}
